name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          fetch-tags: true
      - run: sh ./esy-version/version.sh --reason > ./esy-version/EsyVersion.re
        name: "Generate EsyVersion.re"
      - name: Install esy
        run: npm install -g esy
      - uses: esy/github-action@060fc7176c842a7dad281f4a60d627ca96ae0fc9
        with:
          source-cache-key: 20240515-1
          cache-key: ${{ hashFiles('esy.lock/index.json') }}-20240515-1
      - uses: esy/github-action@060fc7176c842a7dad281f4a60d627ca96ae0fc9
        id: prepare-npm-artifacts
        with:
          source-cache-key: 20240515-1
          cache-key: ${{ hashFiles('esy.lock/index.json') }}-20240515-1
          prepare-npm-artifacts-mode: true

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          files: npm-release.tgz

      - name: Publish to NPM registry
        working-directory: _release
        if: github.ref == 'refs/heads/master'
        run: npm publish --access=public .
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
